---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен автоматически определять язык пользователя
  - Сайт должен сохранять сессию и корзину пользователя
  - Должна быть возможность выбрать какие именно товары заказать из корзины
  - Должна быть возможность убрать конкретное число позиции товаров в корзине, если их несколько
  - Должно быть уведомление о добавлении товара в корзину или визуальное изменение кнопки
  - Сайт должен быть адаптивным
